import Link from "next/link"

export const metadata = { title: "Terms of Service — StudyHub" }

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-3xl mx-auto px-6 py-12 md:py-16">
        <Link href="/" className="text-sm text-primary hover:underline">← Back to StudyHub</Link>
        <h1 className="text-3xl font-bold text-foreground mt-6 mb-2">Terms of Service</h1>
        <p className="text-sm text-muted-foreground mb-10">Last updated: July 2026</p>

        <div className="space-y-8 text-foreground">
          <section>
            <h2 className="text-lg font-semibold mb-2">1. What StudyHub is</h2>
            <p className="text-muted-foreground leading-relaxed">
              StudyHub is a study-planning application: you set a learning goal (or upload a syllabus), and we
              generate a personalized study plan, provide an AI tutor for questions, and generate quizzes to
              check your understanding. New accounts start with a 3-day free trial; continued access after the
              trial requires a paid subscription (Starter or Pro).
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">2. Your account</h2>
            <p className="text-muted-foreground leading-relaxed">
              You're responsible for keeping your password secure and for all activity under your account. You
              must be old enough to legally agree to these terms in your country to sign up. One trial per
              person — creating multiple accounts to repeatedly claim free trials is not permitted.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">3. Subscriptions and billing</h2>
            <p className="text-muted-foreground leading-relaxed">
              Paid plans are billed monthly in advance via Razorpay. Your subscription renews automatically each
              month until you cancel. You can cancel anytime from the Billing page; cancellation takes effect at
              the end of your current billing period, and you keep access until then. See our{" "}
              <Link href="/refund" className="text-primary hover:underline">Refund Policy</Link> for details on
              refunds.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">4. AI-generated content</h2>
            <p className="text-muted-foreground leading-relaxed">
              Study plans, tutor responses, quizzes, and syllabus analysis are generated by AI (currently Google
              Gemini) based on what you provide. AI output can be wrong or incomplete — treat it as a study aid,
              not a substitute for your course materials, textbooks, or instructor guidance. Don't rely on it as
              the sole source for anything graded or high-stakes.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">5. Acceptable use</h2>
            <p className="text-muted-foreground leading-relaxed">
              Don't use StudyHub to upload content you don't have the right to share, to abuse the AI features
              (e.g. automated bulk requests, attempts to extract or resell the underlying AI outputs at scale),
              or to circumvent the trial/subscription limits described above.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">6. Referrals</h2>
            <p className="text-muted-foreground leading-relaxed">
              Referral rewards (free months for referring a friend) are credited only once your referred friend
              becomes a paying subscriber, are capped per referrer, and may be adjusted or revoked if we
              determine the referral system is being abused (e.g. self-referral, fake accounts).
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">7. Changes</h2>
            <p className="text-muted-foreground leading-relaxed">
              We may update these terms as the product evolves. Material changes will be reflected here with an
              updated date. Continued use after a change means you accept the updated terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-2">8. Contact</h2>
            <p className="text-muted-foreground leading-relaxed">
              Questions about these terms: support@studyhub.app
            </p>
          </section>
        </div>
      </div>
    </div>
  )
}
